### ISSUE TITLE
Documentation should specify required Android targets.

### ISSUE THREAD

**Issue by theJenix** [rosjava/android_core#175]
The required Android SDK targets should be listed in the Prerequisites section of the install document.  The groovy-devel branch seems to require android-10, android-13, and android-14 to be present on my machine in order to compile.

**Comment by stonier** [comment]
Actually do specify for the [hydro documentation](http://wiki.ros.org/android/Android%20Studio/Download). So we are aware of it and should be done for future versions.

Closing for now, but reopen with a patch if you really feel it needs an update back to groovy.
