### ISSUE TITLE
Make toast() function protected at MasterChooser.jar (on android_10)

### ISSUE THREAD

**Issue by talregev** [rosjava/android_core#227]
If some drive this class (like i do to extend master-chooser with some ability) , 
he need to copy toast class, or worst, make Toast for himself.

please fix.

Tal.

**Comment by stonier** [comment]
I imagine this got done in your pull request changes to make it protected. Anything else needed?

**Comment by talregev** [comment]
I think it needed by default.
It open source and people will reuse the code.
So why not?

**Comment by stonier** [comment]
@talregev the protected change is already in [here](https://github.com/rosjava/android_core/commit/0bf2a42c88fe6c4e4a7d2c7d3e50dd984d57d0f1#diff-431bd9052f74ff5c47cbc1755f52a0f1L228).

My question - do you need anything else? Can we close this?

**Comment by talregev** [comment]
not as i remember. i will open another if i needed.

**Comment by stonier** [comment]
Aight...thanks! :neckbeard:
