### ISSUE TITLE
Cannot import in Android Studio (or Eclipse)

### ISSUE THREAD

**Issue by kahst** [rosjava/android_core#228]
Importing android_core with "Import Project from Gradle" in Android Studio throws following exception:

Unable to load class 'org.codehaus.groovy.runtime.typehandling.ShortTypeHandling'.

Same with Eclipse Gradle import:
- What went wrong:
  A problem occurred evaluating root project 'android_core-indigo'.
  > org/codehaus/groovy/runtime/typehandling/ShortTypeHandling

Google suggests using a gradle version higher than 2.0 but as far as I know Android Studio only supports gradle 1.10

Thank for your help!

**Comment by stonier** [comment]
The updates for indigo across the board have resolved the ShortTypeHandling problem.

Thanks for the report!
