### ISSUE TITLE
RosCore on Android device results in "No such handler: system.multicall"

### ISSUE THREAD

**Issue by r2DoesInc** [rosjava/android_core#236]
When core is ran on the device - by selecting new public from the master chooser interface - publishing of messages fail.

To test, install and run example app found here - https://github.com/FutureHax/BrokenRos. Create new public through MasterChooser. Point another computer to to ros core instance created by the app. Attempt to publish a message.

`E/XmlRpcErrorLogger( 5201): No such handler: system.multicall
E/XmlRpcErrorLogger( 5201): org.apache.xmlrpc.server.XmlRpcNoSuchHandlerException: No such handler: system.multicall
E/XmlRpcErrorLogger( 5201):     at org.apache.xmlrpc.server.AbstractReflectiveHandlerMapping.getHandler(AbstractReflectiveHandlerMapping.java:214)
E/XmlRpcErrorLogger( 5201):     at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:45)
E/XmlRpcErrorLogger( 5201):     at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
E/XmlRpcErrorLogger( 5201):     at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
E/XmlRpcErrorLogger( 5201):     at org.apache.xmlrpc.webserver.Connection.run(Connection.java:208)
E/XmlRpcErrorLogger( 5201):     at org.apache.xmlrpc.util.ThreadPool$Poolable$1.run(ThreadPool.java:68)`

**Comment by jubeira** [comment]
See https://github.com/rosjava/rosjava_core/issues/84,
ROSJava master does not indeed support multicall; it would be a nice feature to add.

**Comment by jubeira** [comment]
This was fixed in https://github.com/rosjava/rosjava_core/pull/273.

For the record, I tested the ROS master running on Android compiling with this fix, and it worked fine.
