### ISSUE TITLE
Build map_nav got errors

### ISSUE THREAD

**Issue by wennycooper** [rosjava/android_core#240]
I got following errors in building map_nav module in Android Studio.

```
    Error:(161, 16) error: cannot find symbol method addLayer(ViewControlLayer)
    Error:(162, 16) error: cannot find symbol method addLayer(OccupancyGridLayer)
    Error:(163, 16) error: cannot find symbol method addLayer(LaserScanLayer)
    Error:(164, 16) error: cannot find symbol method addLayer(PathLayer)
    Error:(165, 16) error: cannot find symbol method addLayer(MapPosePublisherLayer)
    Error:(166, 16) error: cannot find symbol method addLayer(InitialPoseSubscriberLayer)
```

I post the same problem in ros answer as well. Plz help!!  Thanks!!

http://answers.ros.org/question/220324/building-android_apps-errors-on-android-studio/

**Comment by jubeira** [comment]
Map nav should build properly now.
See https://github.com/rosjava/android_apps/pull/58 and https://github.com/rosjava/android_apps/pull/59.
