### ISSUE TITLE
I want to add Appcompat activity..

### ISSUE THREAD

**Issue by HelloEgg** [rosjava/android_core#248]
I am trying to use pubsub repository and customize in my own way.

The app that I originally built extends AppCompatActivity, views and anyother extensions that needs for normal "Appbuildings"

So I tried adding dependencies 'com.android.support:appcompat-v7:24.2.1' but not surprisingly, build failed with 174 errors... such as:

Error:(229, 21) No resource found that matches the given name: attr 'android:buttonBarStyle'.
Error:(227, 21) No resource found that matches the given name: attr 'android:textColorLinkInverse'.
Error:(224, 21) No resource found that matches the given name: attr 'android:windowActionBar'.
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light'.
Error:(230, 21) No resource found that matches the given name: attr 'android:buttonBarButtonStyle'.
Error:(229, 21) No resource found that matches the given name: attr 'android:buttonBarStyle'.
Error:(227, 21) No resource found that matches the given name: attr 'android:textColorLinkInverse'.
Error:(224, 21) No resource found that matches the given name: attr 'android:windowActionBar'.
Error:(102, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(106, 21) No resource found that matches the given name: attr 'android:colorButtonNormal'.
Error:(104, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(105, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(103, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(100, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(101, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Large'.
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Small'.
Error:(102, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(106, 21) No resource found that matches the given name: attr 'android:colorButtonNormal'.
Error:(104, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(105, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(103, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(100, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(101, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(109, 21) No resource found that matches the given name: attr 'android:windowElevation'.
Error:(102, 21) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(106, 21) No resource found that matches the given name: attr 'android:colorButtonNormal'.
Error:(104, 21) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(105, 21) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(103, 21) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(100, 21) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(101, 21) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(109, 21) No resource found that matches the given name: attr 'android:windowElevation'.
Error:(109, 21) No resource found that matches the given name: attr 'android:windowElevation'.

Any suggestion adding those extension to android core??

**Comment by adamantivm** [comment]
@HelloEgg coincidentally @PerrineAguiar is in the process of contributing an AppCompact activity in #249
Perhaps she can provide some insight on what these errors may be?
Alternatively, you can try using her branch or waiting until the contribution with the added dependency is merged, which should be very soon?

**Comment by adamantivm** [comment]
@HelloEgg can you try now, with the latest version from the kinetic branch? It should already have the dependencies you need.
