### ISSUE TITLE
LaserScanLayer overlapping problem

### ISSUE THREAD

**Issue by tony1213** [rosjava/android_core#251]
When I use Android phone to visualize the "/scan" data,  it occured [this problem](http://answers.ros.org/question/254727/laserscanlayer-overlapping-when-i-subscriber-the-topic-scan/) 

or

[this](http://answers.ros.org/question/91836/left-side-of-laser-scan-visualization-on-android-gets-weird/)

**Comment by adamantivm** [comment]
@tony1213 which Android application are you using to visualize "/scan" data?

**Comment by tony1213** [comment]
This application is developing by myself ,using the Module”android_10“and the Module "android_15".In my Android Application, bulid.gradle(Module app) with this:

> dependencies{
        ...
        compile project(':android_15')
        ...
}

develop platform:
Hardware: [Turtlebot2](http://wiki.ros.org/Robots/TurtleBot) ,  [rplidar A2](http://wiki.ros.org/rplidar)
                  Android Phone:Lenovo PHAB2 PRO 
IDE: [Android Studio 2.2.2](https://developer.android.com/studio/index.html?gclid=CNWA1o2QktICFZRvvAodBrkJqQ)

**Comment by adamantivm** [comment]
OK, we're likely going to be doing some work in this area in the next few weeks. It is not immediate, but we will keep it in mind and update this issue if we find a solution or need more information.

**Comment by tony1213** [comment]
Maybe I solve the problem by manipulate the [LaserScanLayer](https://github.com/rosjava/android_core/blob/kinetic/android_15/src/org/ros/android/view/visualization/layer/LaserScanLayer.java).This is Modified part：

>...
// Calculate the coordinates of the laser range values.
        for (int i = 0; i < ranges.length; i += stride) {
            float range = ranges[i];
            // Ignore ranges that are outside the defined range. We are not overly
            // concerned about the accuracy of the visualization and this is makes it
            // look a lot nicer.
            if (minimumRange < range && range < maximumRange) {
                // x, y, z
                vertexBackBuffer.put((float) (range * Math.cos(angle)));
                vertexBackBuffer.put((float) (range * Math.sin(angle)));
                vertexBackBuffer.put(0);
            } else {
                vertexBackBuffer.put(0);
                vertexBackBuffer.put(0);
                vertexBackBuffer.put(0);
            }
            angle += angleIncrement * stride;
        }
...

**Comment by ernestmc** [comment]
@tony1213 thanks for your report. The problem has been fixed with PR #252. Closing issue.
