### ISSUE TITLE
NodeMainExecutorService leaks RosActivity through NodeMainExecutorServiceListener

### ISSUE THREAD

**Issue by stratomda** [rosjava/android_core#254]
When a RosActivity is destroyed, and the main application is still running, the NodeMainExecutorService contains a reference to the RosActivity preventing it from gc. The fix is to add the ability to remove the NodeMainExecutorServiceListener created in the RosActivity from the NodeMainExecutorService ListenerGroup. This requires ListenerGroup to contain a method for removing a listener (bug filed in rosjava/rosjava_core https://github.com/rosjava/rosjava_core/issues/233).

**Comment by jubeira** [comment]
This was fixed for Indigo but not for Kinetic yet, am I right?

**Comment by stratomda** [comment]
That seems to be correct.

**Comment by adamantivm** [comment]
That was my fault, I screwed something up when I tried to do the update - I got the 0.3.2 to release but failed to push upstream from my local copy. It should be fixed now, but I'd appreciate a second pair of eyes.

**Comment by jubeira** [comment]
LGTM; I think this issue can be closed now.

**Comment by stratomda** [comment]
@adamantivm is this issue still open or was it merged into 0.3.3?

**Comment by adamantivm** [comment]
It's merged and published!
