### ISSUE TITLE
MasterChooser onBackPressed can Causes MainActivity NodeMains to Crash

### ISSUE THREAD

**Issue by stratomda** [rosjava/android_core#266]
If the user navigates back from the MasterChooser activity before a successful Master connection, a class that implements NodeMain and performs a publish (without null checking) can crash. For example, if back is pressed on the android_tutorial_teleop application and the user moves the VirtualJoystickView, the application crashes. 

One solution could be to prevent the user from navigating back from the MasterChooser activity before a connection has been made. Thoughts on adding the following to MasterChooser?
```java
  @Override
  public void onBackPressed() {
    //Prevent user from going back to Launcher Activity since no Master is connected.
    toast("Please connect to a Master!");
  }
```

**Comment by jubeira** [comment]
Oh yes, that is true indeed.
I think you suggestion is OK. 
Another option would be to pause the application and leave it running in the background like when you press "home" (I think that's the default behavior for an Android app, am I right?)
