### ISSUE TITLE
Wiki pages for Lunar

### ISSUE THREAD

**Issue by mikaelarguedas** [rosjava/android_core#269]
@adamantivm heads up, when making lunar the default tab on the wiki I noticed that the following pages have specific content for kinetic and nothing for lunar:
- [x] http://wiki.ros.org/android
- [x] http://wiki.ros.org/android/Tutorials/
- [x] http://wiki.ros.org/rosjava
- [x] http://wiki.ros.org/rosjava/Tutorials

**Comment by adamantivm** [comment]
Thanks @mikaelarguedas ! We're not planning to release rosjava for Lunar, so I've updated those landing pages to point to Kinetic as the latest supported release.

**Comment by johnflux** [comment]
At the moment it's seems impossible to install rosjava on Ubuntu 16.04, or the about-to-be-released 16.10.

What is the plan here?  Is rosjava pretty much dead now?  Is there any plan to release rosjava after Lunar, or is Kinetic the end now?

**Comment by adamantivm** [comment]
@johnflux myself and I know of many other people can successfully use rosjava kinetic on Ubuntu 16.04. Could you please explain what issues that you're facing make you say "it seems impossible to install"?

As one of the current maintainers, I know we unfortunately don't have the time availability to commit to maintain more than the LTR releases of ROS (currently the latest is Kinetic).
But this being an open source project, you are more than welcome to take the lead on doing that. You would receive all of the support of current contributors of this community.

**Comment by johnflux** [comment]
Ah I'm sorry, I meant 17.04 and 17.10  in my last post!

**Comment by adamantivm** [comment]
@johnflux ah, that makes more sense. Yes, there are no binary ROS Kinetic packages available for Ubuntu 17.x.
But it is still possible to build from source and, in the particular case of rosjava, you can even get started on a rosjava project without installing any part of ROS.
You could easily use ROS Lunar and then start your rosjava project pulling the kinetic artifacts directly from maven. Would that not work for you? If so why?
