### ISSUE TITLE
Can we switch to android tools 2.3.2 and gradle 3.3?

### ISSUE THREAD

**Issue by talregev** [rosjava/android_core#270]
Can we switch to "com.android.tools.build:gradle:2.3.2"
and gradle-3.3-all.zip?

**Comment by adamantivm** [comment]
I don't see why not but could you elaborate a bit on the need? Any particular features that would be beneficial?
Also any reason to use the -all package instead of -bin? That would add a considerable amount of download time for the minor benefit of getting gradle sources, which I am not sure are too useful to most rosjava users.

**Comment by talregev** [comment]
Use android 2.3.2 take from [here][1]:

> New:
Uses Gradle 3.3, which includes performance improvements and new features. For more details, see the Gradle release notes.
Build cache: stores certain outputs that the Android plugin generates when building your project (such as unpackaged AARs and pre-dexed remote dependencies). Your clean builds are much faster while using the cache because the build system can simply reuse those cached files during subsequent builds, instead of recreating them. Projects using Android plugin 2.3.0 and higher use the build cache by default. To learn more, read Improve Build Speed with Build Cache.
Includes a cleanBuildCache task that clears the build cache.
If you are using the experimental version of build cache (included in earlier versions of the plugin), you should update your plugin to the latest version.
Changes:
Supports changes to Instant Run included in Android Studio 2.3.
Configuration times for very large projects should be significantly faster.
Fixed issues with auto-downloading for the constraint layout library.
Plugin now uses ProGuard version 5.3.2.
Includes many fixes for reported bugs. Please continue to file bug reports when you encounter issues.

If we start to use Android Plugin 2.3.2, we must move to gradle 3.3.
Already today we use [all build][2] (I guess it happen automatically because android studio).
We can switch to bin.

[1]: https://developer.android.com/studio/releases/gradle-plugin.html
[2]: https://github.com/rosjava/android_core/blob/kinetic/gradle/wrapper/gradle-wrapper.properties#L6

**Comment by talregev** [comment]
I didn't need any feature from 2.3.2. I just thought it more secure. then I read a little more and share.
I wanted to check if there any reason why not. and if it not to complicate to move, maybe we will have a little benefit (performance improvements).

**Comment by adamantivm** [comment]
Ok, cool. Totally possible and a good thing to do. I just wanted to understand urgency and motivation.
It's only a matter of carving out enough time to do it.
If you feel motivated enough to do the migration, please do send PR's and I'll do my best to review quickly.

**Comment by jubeira** [comment]
@talregev at first sight the builds should still work after the upgrade.
I tried using Gradle 3.5.1 manually to build `android_apps` and it seems to work well.
The problem would be to upgrade to Gradle 4.1+, which requires Android build tools > 26. In that case, we will need to tweak the command line tools, as the newer build tools don't have the support to create projects from the command line (see https://github.com/rosjava/rosjava_build_tools/issues/31).

I will do the update when I find some time.

**Comment by talregev** [comment]
ok

**Comment by jubeira** [comment]
We are now at Gradle 4.10; closing this one.
