### ISSUE TITLE
problem with android_tutorial_image_transport

### ISSUE THREAD

**Issue by hungbui-io** [rosjava/android_core#271]
Hey guys,

I'm playing with the android_tutorial_image_transport. I want to show the images from rosbag file on an android device by changing the topic name: `image.setTopicName("/tango/camera/color_1/image_rect/compressed");` but it did not show anything. Why is that? Am I missing something?
Any helps would be much appreciated!

**Comment by adamantivm** [comment]
@hungbv11 as far as I know it should work. Some ideas to orient debugging:
 - Perhaps the problem is that the app is not using the time topic from the bag?
 - Perhaps there is a networking issue between the nodes (try to set `ROS_IP` on the host with the bag before launching the bag reading process)

**Comment by hungbui-io** [comment]
@adamantivm Thanks a lot for your reply
- For time synchronization, I set the /use_sim_time to true and play the bag file with --clock but the app still didn't show anything.
- For the networking issue, I don't quite understand what you means. I did test the android_camera_tutorial and it worked fine without error.
Here are the rqt_graph of the nodes
![screenshot from 2017-07-04 11 47 28](https://user-images.githubusercontent.com/12306168/27825866-4e98b5d6-60b1-11e7-839d-6b5814ca95d3.png)

**Comment by adamantivm** [comment]
@hungbv11 I am sorry I can't tell what could be wrong with that information.
One other suggestion that comes to mind is to try display the image from a live topic instead of a bag file to see if that makes any difference.

**Comment by hungbui-io** [comment]
I wrote a simple node publishing images from laptop webcam but the android app did not subscribe anything :(

**Comment by jubeira** [comment]
Hi @hungbv11,
I'd start by adding more logs to see what's happening exactly.
I would try to avoid simulated clock times at the beginning to discard sources of error (see https://github.com/rosjava/rosjava_core/issues/148).

Perhaps as you say this is not the problem, but just for a reference about networking: http://wiki.ros.org/ROS/Technical%20Overview. It is explained there that all the nodes should be able to resolve each other's address/ name, and setting the variable ROS_IP in the linux side fixes that in some cases.

**Comment by hungbui-io** [comment]
Hey @adamantivm,
I fixed the bug. I forgot to add "export ROS_IP" to the .bashrc file. Here is the the [solution](https://stackoverflow.com/questions/23499359/connecting-to-a-ros-master) for my problem
Anyway, I really appreciate your help!
Cheers
