### ISSUE TITLE
Adding an image publishing node to the android_tutorial_image_transport

### ISSUE THREAD

**Issue by hungbui-io** [rosjava/android_core#272]
Hi guys,

I am wondering about how to add an image publisher to original image_transport tutorial project in order to publish the images from Android camera? 

Here are some ideas I've tried but have not succeeded:

- Use RosCameraPreviewView  (like the android_camera_tutorial did) inside the MainActivity class by adding the[ second nodeConfiguration](http://answers.ros.org/question/186340/using-rosjava-in-android-i-execute-2-nodes-but-only-one-node-connects-at-a-time/)
- Use CompressedImagePublisher from org.ros.android.view.camera
- Write rosjava publisher like [this link](http://rosjava.github.io/rosjava_core/latest/getting_started.html#publishers-and-subscribers)

Do you guys have any suggestion with this issue? Thanks a lot!

**Comment by adamantivm** [comment]
Hi @hungbv11 , the approaches that you mention all sound reasonable. If it was me, I would have started with the second one.
Did you try posting your question in [ROS Answers](http://answers.ros.org/) to see what other fellow users may suggest?

**Comment by jubeira** [comment]
Hi @hungbv11,
I agree with @adamantivm; if you are using Android that's probably the best approach.
If you were using Rosjava alone (without Android), writing a publisher from scratch would work too.
