### ISSUE TITLE
how to listen/publish from/to a service

### ISSUE THREAD

**Issue by vmoysiadis** [rosjava/android_core#277]
Good evening :) 
i am trying to make a service client to my app and i cant figure out how to.
the example with addTwoInts does not cover needs since i got a custom service on my remote PC.

i tryed the examples/answers from ros.answers website but still....

Any ideas ?

**Comment by jubeira** [comment]
Hi @vmoisiadis,
I think this is a rosjava question more than an Android one, and perhaps ROS Answers is a better place for this. Yes, the documentation is certainly outdated.

I haven't done this myself in a while, but here's some hints:
- Install rosjava in your computer. I always prefer installing from source: http://wiki.ros.org/rosjava/Tutorials/kinetic/Source%20Installation (it's not that hard / it doesn't take that long).
- If you source the workspace where rosjava is installed, your system will add rosjava message generators. Every time you do catkin_make, the Java artifacts for the messages you define in the regular ROS way will be created in `ws_root/devel/share/maven`.
- Create a regular ROS package for your messages. You can follow the classic ROS tutorial for that: http://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv.
- Build the workspace using `catkin_make`. You should see the new artifacts appear in the directory above.
- From your bottom level build.gradle script, include the freshly generated artifacts using the full namespace and version number: 
```
    compile 'org.ros.rosjava_messages:your_message_package[1.0.0, 1.1.0)' # Replace your version there; usually leave open the range for the minor number
```
- Sync the gradle project; you should be able to access the new artifacts. If you are using Android studio, source the workspace and then start Android Studio from the same terminal. That should help you with auto complete.

Does that make sense? Sorry for the brief explanation; I will try to make some time myself to write a proper tutorial about this.

You can see an example of all of this working here: https://github.com/intermodalics/tango_ros.

In particular, here are the messages: https://github.com/Intermodalics/tango_ros/tree/master/tango_ros_common/tango_ros_messages (take a look at the package and CMakelists) and here's the `build.gradle` using the generated artifacts: https://github.com/Intermodalics/tango_ros/blob/master/TangoRosStreamer/app/build.gradle#L30. With that example and a bit of patience you should get going :)

To use the messages in the code, it's pretty much like the tutorial. Your messages will have different fields and responses, but the concept is the same.

**Comment by vmoysiadis** [comment]
Thank you so much, you saved me. I followed your instruction and with a little adjustment into my app i was able to import a custom service client

**Comment by jubeira** [comment]
Cool, I'm glad to hear that!
This should be a tutorial, right next to the basic publisher/ subscriber one. I will try to do it when I have some time; please feel free to review it or to comment about it once it's done, so that anyone can follow the same steps properly :smiley:
