### ISSUE TITLE
Releases/Tags do not reflect its commits

### ISSUE THREAD

**Issue by drofwarcs** [rosjava/android_core#285]
I pulled in version 0.3.3 and was getting an error when I tried to access `NodeMainExecutorService.LocalBinder` from my Activity. The issue turned out to be that the LocalBinder nested class does not have the public modifier. However, I noticed that under release https://github.com/rosjava/android_core/releases/tag/0.3.3, there was a merged PR that added the public modifier:  https://github.com/rosjava/android_core/commit/d5ab413f4a573ae62a7aca5071fc6e18d2e0e7b6. 
When I download the source under the same release, that code is without the public modifiers.

Did something else happen to that merge or am I reading the git history wrong:) ?

**Comment by jubeira** [comment]
Hi @drofwarcs,

In this case in particular, the PR was pretty old and targeted to Indigo. It was merged after a long while, and then I made another PR for Kinetic branch; perhaps it came after the tag 0.3.3.

Please try using Master directly. I've been pretty packed up lately; I wanted to do a new release / tag, but I've been short on time.

**Comment by drofwarcs** [comment]
@jubeira master worked like a charm. Thanks 👍
