### ISSUE TITLE
Failed to resolve: org.ros - following tutorial

### ISSUE THREAD

**Issue by bawboc** [rosjava/android_core#299]
I am attempting to follow the tutorial at [http://wiki.ros.org/android/Tutorials/kinetic/Installation%20-%20Android%20Studio%20Development%20Environment](http://wiki.ros.org/android/Tutorials/kinetic/Installation%20-%20Android%20Studio%20Development%20Environment) .  When I try to build this project, I get the error `Failed to resolve: ros.org` for this segment:
`dependencies {
    ...
    // You now now add any rosjava dependencies, like so:
        implementation 'org.ros.android_core:android_core_components:0.4.0'
}`

**Comment by jubeira** [comment]
Hi @bawboc,

Would you please try building https://github.com/rosjava/android_apps? That line should bring the dependency from `rosjava_mvn_repo`.

E.g. in teleop app the dependency is specified like that, and the app should work:
https://github.com/rosjava/android_apps/blob/kinetic/teleop/build.gradle#L19

**Comment by bawboc** [comment]
Thanks,

  That builds just fine.  I was also able to build the android_core
projects.  It is just the tutorial I linked that I am having difficulties
with.  I was hoping to have a seperate project instead of having to add
onto the existing android_core or android_apps projects.

James

**Comment by jubeira** [comment]
Have you applied the buildscript from the upstream repository in the top-level `build.gradle` as in here? https://github.com/rosjava/android_apps/blob/kinetic/build.gradle#L22. That's the line that adds rosjava's Maven repository, allowing to resolve those dependencies properly.

**Comment by bawboc** [comment]
Yes I did.  But I had a typo.  Thank you so much for your time.  It's building now.
