### ISSUE TITLE
cannot receive messages from apps.

### ISSUE THREAD

**Issue by talregev** [rosjava/android_core#301]
It happen also in ros images messages. Here I am show simple way to reproduce the problem. 

1. install ros kinetic.
2. install pubsub tutorial app
3. open `roscore` on computer
4. connect pubsub app with your computer ip.
5. on computer type `rostopic echo /chatter`

expected to see ros messages hello world.

did not receive any messages.

**Comment by stringnotfound1** [comment]
Since I managed to get the pubsub example running with out any issues you might want to check if you setup the [name resolution](http://wiki.ros.org/ROS/NetworkSetup#Name_resolution) on your computer that is running roscore.

You might also want to check logcat if you get any network related errors or warnings, e.g. that the host could not be resolved.

**Comment by jubeira** [comment]
@talregev I was going to suggest the same.
Try setting `ROS_IP` environment variable on the computer running `roscore`. It's likely that the Android device is not being able to resolve the hostname, so forcing the IP address might solve the problem.

Let us know if that works!

**Comment by talregev** [comment]
Thanks for your quick response!   

I try with ROS_IP to give roscore the computer ip.   
Also try to create roscore on the phone. It connect but still the computer did not receive messages.    
Not sure what i am doing wrong.     

![roscore](https://user-images.githubusercontent.com/7043539/56596131-a3729100-65f8-11e9-9eeb-542a3d707dab.PNG)
![rostopic](https://user-images.githubusercontent.com/7043539/56596132-a40b2780-65f8-11e9-94a9-b54f09c8b7fb.PNG)

**Comment by jubeira** [comment]
can you do `rostopic info /chatter` to see who's publishing and subscribing to the topic? This sounds like a common network issue.

**Comment by talregev** [comment]
It works also with melodic!   
For me it only work when I use hotspot with computer and phone.   
When computer and phone connect to the same router (network),   
it does not work for me. not sure how to fix it.

**Comment by stringnotfound1** [comment]
Are you testing it in your own home network or at work? It could be possible that some ports get blocked in the network that you are connecting to due to security reasons.

If you haven't already please check logcat for any network related errors or warnings.

**Comment by talregev** [comment]
I am using my home network.     
Not sure where is the problem in my network.    
Right now I am not near my network, So when I try again, I will post my attempts.    
For now I have workaround.     
Thanks for yours help! :)
