### ISSUE TITLE
Cannot subscribe to any topic running on a linux host

### ISSUE THREAD

**Issue by chadrockey** [rosjava/android_core#86]
_Original author: nuclearm...@gmail.com (February 02, 2012 17:23:26)_

<b>What steps will reproduce the problem?</b>
1. subscribe to any topic running on a linux host
2. get a timeoutexception in the requestpublishers xmlrpc code

<b>What is the expected output? What do you see instead?</b>
Not an exception. An exception, and a distinct lack of receiving published messages.

What version of the product are you using? Latest version of video tutorial running on Android4.0.2

Have tried various remote masters running on linux boxes ranging from 10.04-64bit to 11.04-64bit. The subscription and messages work fine in the linux-to-linux situation.

At some point, these features worked, but the android sdk has changed physically since then, so building the old non-broken version is insufficient.

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=86_

**Comment by chadrockey** [comment]
_From nuclearm...@gmail.com on February 02, 2012 17:25:42_
(the remote master is running Electric, but I don't believe the guts of XmlRpcCpp nor the master<->node negotiations have changed.

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on February 02, 2012 17:28:18_
Could you please post the stack trace? I am not able to reproduce this issue.

**Comment by chadrockey** [comment]
_From nuclearm...@gmail.com on February 02, 2012 18:26:19_
The exception is caught by the rosjava code, and shows up in logcat.

org.ros.tutorial.prime is the teleop tutorial with the package ID and a few topic names changed. RosJava itself wasn't altered.

I/ActivityManager(  207): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ros.android.tutorial.prime/.MainActivity} from pid 469
I/WindowManager(  207): createSurface Window{41ad5a30 Starting org.ros.android.tutorial.prime paused=false}: DRAW NOW PENDING
I/InputReader(  207): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  207): Device reconfigured: id=6, name='Melfas MMSxxx Touchscreen', surface size is now 720x1280, mode is 1
I/ActivityManager(  207): Config changed: {1.0 310mcc410mnc en_US layoutdir=0 sw360dp w598dp h360dp nrml land finger -keyb/v/h -nav/h s.28}
D/OpenGLRenderer(  282): Flushing caches (mode 0)
D/OpenGLRenderer(  282): Flushing caches (mode 0)
I/ActivityManager(  207): START {cmp=org.ros.android.tutorial.prime/org.ros.android.MasterChooser} from pid 3878
D/dalvikvm( 3878): GC_CONCURRENT freed 477K, 5% free 15757K/16455K, paused 3ms+4ms
I/WindowManager(  207): createSurface Window{41b9aba0 org.ros.android.tutorial.prime/org.ros.android.MasterChooser paused=false}: DRAW NOW PENDING
D/OpenGLRenderer(  469): Flushing caches (mode 0)
I/ActivityManager(  207): Displayed org.ros.android.tutorial.prime/org.ros.android.MasterChooser: +419ms (total +713ms)
D/OpenGLRenderer(  469): Flushing caches (mode 1)
D/OpenGLRenderer(  469): Flushing caches (mode 0)
W/IInputConnectionWrapper(  469): showStatusIcon on inactive InputConnection
W/InputManagerService(  207): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@41d6d020 (uid=10029 pid=469)
D/dalvikvm(  207): GC_EXPLICIT freed 449K, 14% free 20725K/23879K, paused 6ms+4ms
D/dalvikvm(  282): GC_CONCURRENT freed 540K, 7% free 16150K/17287K, paused 5ms+10ms
W/Gmail   ( 4076): No MailEngine for account: munjal.desai@gmail.com
V/PicasaContentProvider(  704): querySettings: defaults: {sync_on_wifi_only=1, auto_upload_account_type=null, sync_on_battery=1, sync_picasa_on_wifi_only=1, auto_upload_enabled=0, video_upload_wifi_only=1, sync_on_roaming=0, auto_upload_account_name=null}
I/WindowManager(  207): createSurface Window{41ad9568 org.ros.android.tutorial.prime/org.ros.android.tutorial.prime.MainActivity paused=false}: DRAW NOW PENDING
D/OpenGLRenderer( 3878): Flushing caches (mode 0)
I/ActivityManager(  207): Displayed org.ros.android.tutorial.prime/.MainActivity: +1m26s173ms
D/dalvikvm( 3878): GC_CONCURRENT freed 1110K, 8% free 15192K/16455K, paused 6ms+5ms
D/dalvikvm( 3878): GC_FOR_ALLOC freed 135K, 6% free 15541K/16455K, paused 30ms
D/dalvikvm( 3878): GC_CONCURRENT freed 38K, 5% free 15682K/16455K, paused 4ms+3ms
I/DefaultPublisher( 3878): Subscriber registered: Subscriber<TopicDefinition<TopicIdentifier</gscam/image_raw>, MessageDefinition<sensor_msgs/Image, 060021388200f6f0f447d0fcd9c64743>>>
I/DefaultPublisher( 3878): Publisher registered: Publisher<PublisherDefinition<PublisherIdentifier<NodeSlaveIdentifier</android/video_view, http://10.0.2.105:45344>, TopicIdentifier</rosout>>, TopicDefinition<TopicIdentifier</rosout>, MessageDefinition<rosgraph_msgs/Log, acffd30cd6b6de30f120938c17c593fb>>>>
I/System.out( 4131): [INFO:904192]: c: Running flush
I/System.out( 4131): [INFO:904215]: c: Sending payload [bytes=591]
D/dalvikvm(  282): GC_FOR_ALLOC freed 382K, 7% free 16155K/17287K, paused 32ms
D/dalvikvm( 4131): GC_CONCURRENT freed 324K, 3% free 15261K/15687K, paused 3ms+4ms
I/System.out( 4131): [INFO:904989]: c: Response [http=200,length=20]
I/System.out( 4131): [INFO:904992]: c: Read id 1, status code 200
I/InputReader(  207): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  207): Device reconfigured: id=6, name='Melfas MMSxxx Touchscreen', surface size is now 720x1280, mode is 1
I/ActivityManager(  207): Config changed: {1.0 310mcc410mnc en_US layoutdir=0 sw360dp w360dp h592dp nrml port finger -keyb/v/h -nav/h s.29}
D/OpenGLRenderer(  282): Flushing caches (mode 0)
D/OpenGLRenderer( 3878): Flushing caches (mode 0)
D/OpenGLRenderer( 3878): Flushing caches (mode 1)
W/ActivityManager(  207): Duplicate finish request for ActivityRecord{41ac9858 org.ros.android.tutorial.prime/.MainActivity}
I/WindowManager(  207): createSurface Window{41ca74e8 com.android.launcher/com.android.launcher2.Launcher paused=false}: DRAW NOW PENDING
I/DefaultPublisher( 3878): Subscriber unregistered: Subscriber<TopicDefinition<TopicIdentifier</gscam/image_raw>, MessageDefinition<sensor_msgs/Image, 060021388200f6f0f447d0fcd9c64743>>>
I/System.out( 3878): Shutdown successful.
D/OpenGLRenderer(  282): Flushing caches (mode 0)
I/WindowManager(  207): createSurface Window{41efe160 Toast paused=false}: DRAW NOW PENDING
W/IInputConnectionWrapper( 3878): showStatusIcon on inactive InputConnection
D/dalvikvm(  207): GC_EXPLICIT freed 1062K, 14% free 20671K/23879K, paused 6ms+5ms
I/ActivityManager(  207): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ros.android.tutorial.prime/.MainActivity} from pid 469
I/WindowManager(  207): createSurface Window{41c367e8 Starting org.ros.android.tutorial.prime paused=false}: DRAW NOW PENDING
I/InputReader(  207): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  207): Device reconfigured: id=6, name='Melfas MMSxxx Touchscreen', surface size is now 720x1280, mode is 1
I/ActivityManager(  207): Config changed: {1.0 310mcc410mnc en_US layoutdir=0 sw360dp w598dp h360dp nrml land finger -keyb/v/h -nav/h s.30}
D/OpenGLRenderer(  282): Flushing caches (mode 0)
I/ActivityManager(  207): START {cmp=org.ros.android.tutorial.prime/org.ros.android.MasterChooser} from pid 3878
D/OpenGLRenderer(  282): Flushing caches (mode 0)
D/OpenGLRenderer(  469): Flushing caches (mode 0)
D/dalvikvm( 3878): GC_CONCURRENT freed 352K, 5% free 15781K/16455K, paused 4ms+6ms
I/WindowManager(  207): createSurface Window{41d97128 org.ros.android.tutorial.prime/org.ros.android.MasterChooser paused=false}: DRAW NOW PENDING
I/ActivityManager(  207): Displayed org.ros.android.tutorial.prime/org.ros.android.MasterChooser: +395ms (total +706ms)
D/OpenGLRenderer(  469): Flushing caches (mode 1)
D/OpenGLRenderer(  469): Flushing caches (mode 0)
W/IInputConnectionWrapper(  469): showStatusIcon on inactive InputConnection
W/InputManagerService(  207): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@41d6d020 (uid=10029 pid=469)
I/WindowManager(  207): createSurface Window{41d5a740 PopupWindow:419b9fd8 paused=false}: DRAW NOW PENDING
I/InputReader(  207): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  207): Device reconfigured: id=6, name='Melfas MMSxxx Touchscreen', surface size is now 720x1280, mode is 1
I/ActivityManager(  207): Config changed: {1.0 310mcc410mnc en_US layoutdir=0 sw360dp w360dp h592dp nrml port finger -keyb/v/h -nav/h s.31}
D/OpenGLRenderer(  282): Flushing caches (mode 0)
D/OpenGLRenderer( 3878): Flushing caches (mode 0)
D/OpenGLRenderer(  282): Flushing caches (mode 0)
I/WindowManager(  207): createSurface Window{41b67c00 org.ros.android.tutorial.prime/org.ros.android.MasterChooser paused=false}: DRAW NOW PENDING
D/dalvikvm(  421): GC_CONCURRENT freed 1976K, 18% free 16069K/19463K, paused 2ms+3ms
I/WindowManager(  207): createSurface Window{41d5ca18 InputMethod paused=false}: DRAW NOW PENDING
I/WindowManager(  207): createSurface Window{41c76868 TrackingView paused=false}: DRAW NOW PENDING
D/dalvikvm(  207): GC_EXPLICIT freed 880K, 14% free 20743K/23879K, paused 6ms+5ms
D/OpenGLRenderer(  282): Flushing caches (mode 0)
W/InputManagerService(  207): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41b2a738
I/WindowManager(  207): createSurface Window{41c32ce0 PopupWindow:41922698 paused=false}: DRAW NOW PENDING
I/WindowManager(  207): createSurface Window{41d5ca18 InputMethod paused=false}: DRAW NOW PENDING
D/dalvikvm(  421): GC_FOR_ALLOC freed 542K, 18% free 16011K/19463K, paused 23ms
I/dalvikvm-heap(  421): Grow heap (frag case) to 16.926MB for 1278736-byte allocation
D/dalvikvm(  421): GC_CONCURRENT freed 39K, 12% free 17221K/19463K, paused 2ms+2ms
I/WindowManager(  207): createSurface Window{41d98628 PopupWindow:41adde70 paused=false}: DRAW NOW PENDING
I/WindowManager(  207): createSurface Window{41b57528 PopupWindow:41adde70 paused=false}: DRAW NOW PENDING
I/WindowManager(  207): createSurface Window{41e15290 PopupWindow:41adde70 paused=false}: DRAW NOW PENDING
I/InputReader(  207): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  207): Device reconfigured: id=6, name='Melfas MMSxxx Touchscreen', surface size is now 720x1280, mode is 1
I/ActivityManager(  207): Config changed: {1.0 310mcc410mnc en_US layoutdir=0 sw360dp w598dp h360dp nrml land finger -keyb/v/h -nav/h s.32}
D/OpenGLRenderer(  282): Flushing caches (mode 0)
D/OpenGLRenderer(  282): Flushing caches (mode 0)
D/OpenGLRenderer( 3878): Flushing caches (mode 0)
I/WindowManager(  207): createSurface Window{41cd3608 org.ros.android.tutorial.prime/org.ros.android.tutorial.prime.MainActivity paused=false}: DRAW NOW PENDING
D/dalvikvm( 3878): GC_CONCURRENT freed 1075K, 8% free 15289K/16455K, paused 2ms+4ms
I/ActivityManager(  207): Displayed org.ros.android.tutorial.prime/.MainActivity: +15s985ms
W/IInputConnectionWrapper( 3878): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper( 3878): getExtractedText on inactive InputConnection
E/InputMethodService(  421): Unexpected null in startExtractingText : mExtractedText = null, input connection = com.android.internal.view.InputConnectionWrapper@4191f218
D/dalvikvm( 3878): GC_CONCURRENT freed 320K, 6% free 15484K/16455K, paused 9ms+14ms
I/DefaultPublisher( 3878): Publisher registered: Publisher<PublisherDefinition<PublisherIdentifier<NodeSlaveIdentifier</android/video_view, http://10.0.2.105:52723>, TopicIdentifier</rosout>>, TopicDefinition<TopicIdentifier</rosout>, MessageDefinition<rosgraph_msgs/Log, acffd30cd6b6de30f120938c17c593fb>>>>
D/dalvikvm(  421): GC_CONCURRENT freed 2124K, 18% free 16093K/19463K, paused 2ms+5ms
I/DefaultPublisher( 3878): Subscriber registered: Subscriber<TopicDefinition<TopicIdentifier</gscam/image_raw>, MessageDefinition<sensor_msgs/Image, 060021388200f6f0f447d0fcd9c64743>>>
D/dalvikvm(  421): GC_FOR_ALLOC freed 122K, 18% free 15971K/19463K, paused 25ms
I/dalvikvm-heap(  421): Grow heap (frag case) to 17.247MB for 1655280-byte allocation
D/dalvikvm( 3878): GC_CONCURRENT freed 122K, 5% free 15782K/16455K, paused 3ms+2ms
D/dalvikvm(  421): GC_CONCURRENT freed <1K, 10% free 17588K/19463K, paused 2ms+4ms
D/dalvikvm(  282): GC_CONCURRENT freed 520K, 7% free 16235K/17287K, paused 2ms+5ms
E/InputMethodService(  421): Unexpected null in startExtractingText : mExtractedText = null, input connection = com.android.internal.view.InputConnectionWrapper@41a086c0
D/dalvikvm(  207): GC_EXPLICIT freed 1032K, 14% free 20686K/23879K, paused 6ms+6ms
E/UpdatePublisherRunnable( 3878): org.ros.internal.node.xmlrpc.XmlRpcTimeoutException: org.apache.xmlrpc.client.TimingOutCallback$TimeoutException: No response after waiting for 10000 milliseconds.

The above occured when I connected to master after having already started the node publishing the topic.

I also tried connecting to master on the phone before starting the publisher on my ubuntu machine, and found that the UpdatePublisherRunnable error did not occur until 10 seconds after the publisher for the topic started.

We've recreated the same exception by subscribing to /rosout on the android phone running the rosjava-wielding app, as well.

**Comment by chadrockey** [comment]
_From nuclearm...@gmail.com on February 02, 2012 18:33:41_
Here is the compiled app... the topic it's trying to listen to is /gscam/image_raw... we ran the publishing node using the default "how to run" code on http://www.ros.org/wiki/gscam, but have had the same issue trying to stream data from a Kinect on the default topic in the openni.launch launch file (/camera/rgb/image_color).

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on February 02, 2012 18:36:25_
The timeout occurs when the node is unable to contact the master. Please make sure that you've used the correct URI for the master and that it is accessible from the device.

Please share the snippet of code you're using to construct your NodeConfiguraiton.

Also, unless you're using the released version of rosjava, please hg pull to be sure you're using the latest version from head.

**Comment by chadrockey** [comment]
_From nuclearm...@gmail.com on February 02, 2012 18:47:38_
It is able to publish joystick messages... the timeout only occurs in the subscription.

We've tried the latest version, the version before that, and a few "unknown age" versions.

The only one we've been able to actually use was ~8 months old (and we only have the APK for it... no source code, and no built rosjava with which to build new apps)... with it (the ~8 month old app), we were able to publish one phone's camera to another phone, both using a RosElectric master on a ubuntu 10.04 box.

**Comment by chadrockey** [comment]
_From nuclearm...@gmail.com on February 02, 2012 18:49:16_
It contacts master fine... the connection only occurs after the publisher for its topic connects... it's not the xmlrpc client initialization that fails... it's able to see the functions registered on the xmlrpc server in master... it just fails to execute its callback when it actually hears from master that there's a publisher for the topic it wants.

**Comment by chadrockey** [comment]
_From nuclearm...@gmail.com on February 02, 2012 18:51:25_
As for the code snippet, it's literally the teleop tutorial app. All we've changed is the name of the image topic.

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on April 04, 2012 07:46:08_
I cannot reproduce this issue.

**Comment by arpit-korechi** [comment]
Try restarting services from the robot system and reconnecting the tablet was work for me. I think the problem in my case was the after doing cold start services from robots are not starting.
